### ISSUE TITLE
More reliable way to get the userAgent

### ISSUE THREAD

**Issue by moreindirection** [ksmandersen/GoogleReporter#10]
https://github.com/ksmandersen/GoogleReporter/blob/ea9bce17695e69f0c39221d0b5f188b49e942a74/GoogleReporter.swift#L214

Instead of putting this string together from scratch, you can call:

    let webView = UIWebView(frame: .zero)
    let userAgent = webView.stringByEvaluatingJavaScript(from: "navigator.userAgent")

on iOS. On macOS, there's the slightly nicer:

   let webView = WebView(frame: .zero)
   let userAgent = webView.userAgent(for: baseURL)

**Comment by ksmandersen** [comment]
@moreindirection This is amazing if true. I'll have to take a closer look. One problem however is tvOS where WebView is not available. So there needs to be another solution for that still.

**Comment by ksmandersen** [comment]
Fixed in 2940d0f08180f8113720fe5cdfb9bd83e5e18bcc
