### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by vanshg** [ksmandersen/GoogleReporter#2]
It would be great if this could support macOS as well! Maybe it already can, but it doesn't seem to explicitly say so in the README file

**Comment by ksmandersen** [comment]
It should be possible to port make this work on macOS. I haven't done a lot of macOS myself by there are a few problem areas.

The screen resolution relies on ``UIScreen`` from ``UIKit``. This will probably need to use ``NSScreen`` from ``AppKit`` instead. [See here](https://github.com/ksmandersen/GoogleReporter/blob/master/GoogleReporter.swift#L168-L171)

The user agent is using ``UIDevice`` from ``UIKit`` to generate a correct user agent  for GA that will allow correct categorizations of the browsing device. This will need to user another API on macOS. Maybe this can be obtained with ``ProcessInfo`` from ``Foundation``. [See here](https://github.com/ksmandersen/GoogleReporter/blob/master/GoogleReporter.swift#L134-L138)

You're more that welcome to open up PR. I have something in the works, but will need to add some tests to verify that it works as intended on macOS

**Comment by vanshg** [comment]
Attempting to resolve this with https://github.com/ksmandersen/GoogleReporter/pull/3

**Comment by ksmandersen** [comment]
@vanshg Released in 1.1 (https://github.com/ksmandersen/GoogleReporter/releases/tag/1.1)
Help testing this, much appreciated 👌
