### ISSUE TITLE
screen bounds should not be affected by device orientation

### ISSUE THREAD

**Issue by moreindirection** [ksmandersen/GoogleReporter#9]
https://github.com/ksmandersen/GoogleReporter/blob/ea9bce17695e69f0c39221d0b5f188b49e942a74/GoogleReporter.swift#L252

This should call `nativeBounds`. `bounds` is affected by whether the device is in landscape or portrait mode, but `nativeBounds` returns the canonical screen size.

**Comment by ksmandersen** [comment]
@moreindirection Makes sense. Would you consider opening a PR?

**Comment by ksmandersen** [comment]
Fixed in 974c3c3cd5c9cdc9bca5e1eebd7a430be073d093
